// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sucydrdhwyokmphkicec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y3lkcmRod3lva21waGtpY2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NzM1NzMsImV4cCI6MjA1NTU0OTU3M30.gym90OMhbq-1bn_aoA8iePq4ew6LM5S0S80P6_eKO_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);